import "./globals.css";
import { getServerSession } from "next-auth";
import AuthProvider from "../src/providers/AuthProvider"; // Import your AuthProvider


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // Fetch the session on the server side
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
      <AuthProvider session={session}>
        {children}
      </AuthProvider>
      </body>
    </html>
  );
}
